### ISSUE TITLE
[FEATURE] Convert all issue templates into issue forms

### ISSUE THREAD

**Issue by Panquesito7** [dscnitrourkela/project-oregano#127]
**Is your feature request related to a problem? Please describe.**

[Issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) is a new way of making issues in GitHub. IMO, we should use them here, too.

**Describe the solution you'd like**

Convert issue templates into all issue forms.

**Additional context**

I can work on this if wanted. Please let me know! 🙂

**Comment by CIPHERTron** [comment]
Heyy @Panquesito7 issue forms would be a great enhancement. Would you like to work on it?

**Comment by Panquesito7** [comment]
> Heyy @Panquesito7 issue forms would be a great enhancement. Would you like to work on it?

Sure! I'll work on it today. Thanks. 😄
