### ISSUE TITLE
feat: Add Meta Tags

### ISSUE THREAD

**Issue by CIPHERTron** [dscnitrourkela/project-oregano#27]
Reference: https://github.com/dscnitrourkela/project-kiwi/blob/dev/pages/index.js

**Comment by DesignrKnight** [comment]
@CIPHERTron Can you get the content for the meta-tags added here. The image description and other stuffs. Would make the work of developer easier if the content is provided from content and design team

**Comment by CIPHERTron** [comment]
Roger that @DesignrKnight 💪🏻

**Comment by riteshsp2000** [comment]
Anyone working on this ping me. There are quite a few things that we can do to increase our SEO, not just meta tags but structured data which will help in google search results.

**Comment by riteshsp2000** [comment]
A few resources regarding the SEO implementations.

1. Generic Meta Tags for SEO
- A common component that adds all the meta tags is already created in the components/shared/SEO directory.
- Get the content for the required from the content team and pass it props to the component accordingly.
- Note: All the content should be in the /config/content directory.

2. Structured Data.
- Structured data is basically a specific json that is added inside meta tags which is then used by search engines to directly list your mentioned data in the search console. Add the following structured data.
- [Event Structured Data](https://developers.google.com/search/docs/data-types/event): Used to show an upcoming event on the Search page.
- [FAQ](https://developers.google.com/search/docs/data-types/faqpage): Used to show our FAQs in the Google Search page.
- [Breadcrumbs](https://developers.google.com/search/docs/data-types/breadcrumb): Shortcut links to various sections directly in the search page.

**Comment by Sonakshi1901** [comment]
I am interested in this issue.
