### ISSUE TITLE
feat: Make Gatsby Site a PWA

### ISSUE THREAD

**Issue by CIPHERTron** [dscnitrourkela/project-oregano#28]
Reference: https://www.digitalocean.com/community/tutorials/gatsbyjs-gatsby-pwa

**Comment by riteshsp2000** [comment]
Configure gatsby with different plugins, following are a few
1. Gatsby Image
2. Manifest
3. Site metadata
4. Gatsby Plugin Sharp and Transform Sharp
5. Offline
6. Sitemap and Robots
7. Netlify
8. Google Analytics
