### ISSUE TITLE
bug: No Breakpoints Added In Typography Elements

### ISSUE THREAD

**Issue by CIPHERTron** [dscnitrourkela/project-oregano#38]
In the typography elements like Heading1, Heading2, and others, only the normal view font sizes are mentioned. They don't have breakpoints. 
Eg: Heading1 element will have a 5xl size in all the views(Desktop, iPad, mobile) but what we require is that it should be able to resize itself according to the dimensions it is currently displayed in. (basically breakpoints)

**Comment by abhibhaw** [comment]
@SriramPatibanda would u like to work on this issue?

**Comment by gouravmohanty7070** [comment]
Interested

**Comment by CIPHERTron** [comment]
Cool, assigning it to you @gouravmohanty7070. All the best!
