### ISSUE TITLE
config: Add Necessary Plugins in Gatsby Config

### ISSUE THREAD

**Issue by CIPHERTron** [dscnitrourkela/project-oregano#45]
As of now, the main plugin is `gatsby-plugin-styled-components` & `styled-components babel-plugin-styled-components`
This will most likely solve the issue of CSS loading late. Rest, up to you @riteshsp2000 to add the necessary plugins.

**Comment by riteshsp2000** [comment]
I have referenced this in the Gatsby PWA issue since that is a plugin as well. Hence closing this issue.

**Comment by CIPHERTron** [comment]
Ohh...okay cool
