### ISSUE TITLE
Implement smooth scrolling to different sections of the website

### ISSUE THREAD

**Issue by CIPHERTron** [dscnitrourkela/project-oregano#56]
# Reference:

## Preference-1: `gatsby-plugin-smoothscroll`
https://www.gatsbyjs.com/plugins/gatsby-plugin-smoothscroll/

## Preference-2: `gatsby-plugin-scroll-reveal`
https://www.gatsbyjs.com/plugins/gatsby-plugin-scroll-reveal/

## Preference-3: `gatsby-plugin-anchor-links`
https://www.gatsbyjs.com/plugins/gatsby-plugin-anchor-links/

## Preference-4: `react-scroll`
https://www.npmjs.com/package/react-scroll
https://www.digitalocean.com/community/tutorials/how-to-implement-smooth-scrolling-in-react

**Comment by padmajabhol** [comment]
I'd like to work on this.
