### ISSUE TITLE
Add Content In The Website

### ISSUE THREAD

**Issue by nayakastha** [dscnitrourkela/project-oregano#59]
Website Intro - https://www.notion.so/Website-Intro-Part-7cf9607b722144afa86ec0ece8b30e66
Tracks and description - https://www.notion.so/Tracks-628123671487421d9bc637ef7d3274ab
Sponsorship - https://www.notion.so/Sponsors-b54236d437344656950f2c57b253f16c
FAQ - https://www.notion.so/FAQ-9b3913525d7541a8ab5e1e12f063c24d
Be a Hacker section - https://www.notion.so/Be-a-hacker-Harsh-and-f90558ff2d77470696691dc31298451d
Footer - https://www.notion.so/Footer-74c8d399e98345bd88f89eaddc6171d1

Some parts are still in the process of change.
@riteshsp2000 and @CIPHERTron check if you guys have access to the pages

**Comment by sambit-sankalp** [comment]
I want to work on this!! Can you grant me the access?
