### ISSUE TITLE
Add Sponsor logos In the Website

### ISSUE THREAD

**Issue by CIPHERTron** [dscnitrourkela/project-oregano#66]

**Comment by nayakastha** [comment]
Another important part of it is the Authentication Partner category. 
We have SAWO Labs as authentication partner

**Comment by ORKO06** [comment]
Gamma:-Taskade :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/gamma/vgblcn40kjajxwxmph68.png

**Comment by CIPHERTron** [comment]
@padmajabhol I'm assigning it to you!

**Comment by padmajabhol** [comment]
> @padmajabhol I'm assigning it to you!

Sure!

**Comment by ORKO06** [comment]
Alpha

Diamond Jubilee :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/alpha/ogaeyl6batos4n5cumtz.png
github :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/alpha/oigy7pgs2haeoh8dtqon.png
devfolio :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/alpha/vlnvmirmr4r7tolmdrxt.png


Beta

tezos :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/beta/pc6gl1q0iojabd98zfde.png
celo :-  https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/beta/ogjutyp26djnh9lrzybl.png
polygon :-  https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/beta/ag8zpyl5g1ldxpxgfslh.png


Gamma:- 

Taskade :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/gamma/vgblcn40kjajxwxmph68.png
Wolfram :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/gamma/yukdnno6o2y2hdbddnrk.png
Voiceflow :- https://res.cloudinary.com/dalqfvowk/image/uploadproject-oregano/sponsors/gamma/hendtn2wfa16wyuxk7so.png
EchoAR :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/gamma/xffabbcsz6p7ddyp3li0.png


Delta

tweetbeam:- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/delta/wx7rpjho44bemgfrsgl9.png
linode:- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/delta/jcr1qdx3oivszgrpxqml.png
repl.it :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/delta/vs6j6vhnblodwddpnxeu.png
leading learners :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/delta/aksbtyjd4h8ekwtlwt2u.png

**Comment by padmajabhol** [comment]
> Alpha
> 
> Diamond Jubilee :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/alpha/ogaeyl6batos4n5cumtz.png
> github :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/alpha/oigy7pgs2haeoh8dtqon.png
> devfolio :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/alpha/vlnvmirmr4r7tolmdrxt.png
> 
> Beta
> 
> tezos :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/beta/pc6gl1q0iojabd98zfde.png
> celo :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/beta/ogjutyp26djnh9lrzybl.png
> polygon :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/beta/ag8zpyl5g1ldxpxgfslh.png
> 
> Gamma:-
> 
> Taskade :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/gamma/vgblcn40kjajxwxmph68.png
> Wolfram :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/gamma/yukdnno6o2y2hdbddnrk.png
> Voiceflow :- https://res.cloudinary.com/dalqfvowk/image/uploadproject-oregano/sponsors/gamma/hendtn2wfa16wyuxk7so.png
> EchoAR :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/gamma/xffabbcsz6p7ddyp3li0.png
> 
> Delta
> 
> tweetbeam:- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/delta/wx7rpjho44bemgfrsgl9.png
> linode:- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/delta/jcr1qdx3oivszgrpxqml.png
> repl.it :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/delta/vs6j6vhnblodwddpnxeu.png
> leading learners :- https://res.cloudinary.com/dalqfvowk/image/upload/project-oregano/sponsors/delta/aksbtyjd4h8ekwtlwt2u.png

Voiceflow's link isn't working, can you please look into it? @ORKO06

**Comment by CIPHERTron** [comment]
Great job @ORKO06 
Thank you so much🙌🙌

**Comment by ORKO06** [comment]
@padmajabhol   I have updated the Voiceflow's link and added the Sticker mule link
