### ISSUE TITLE
feat: Add new sponsors in the list

### ISSUE THREAD

**Issue by nayakastha** [dscnitrourkela/project-oregano#86]
This will be a permanent issue. We will add the sponsor names in a comment, the assigned person will add the respective sponsor to the website.

**DO NOT CLOSE THIS ISSUE**
---
comment format
  1. Sponsor Display Name
  2. Serial Number
  3. Sponsor Logo required format ( @ORKO06 will add the `Cloudinary` link)
  4. Redirect Link
  5. Sponsor Tier
---
 @ORKO06 comment format 
  1. Serial Number
  2.  Cloudflare link

**Comment by padmajabhol** [comment]
@ORKO06 do update the cloudinary link.

**Comment by Smrutismita109** [comment]
1.Wolfram
2.Sr No.2
3.Logo
![wolfram](https://user-images.githubusercontent.com/87279073/131225704-5580515e-810d-4400-a4ad-3a8ff3983fc7.jpg)
4. https://www.wolfram.com
5. Gamma

**Comment by Smrutismita109** [comment]
1.Filter_Beans
2. Sr No. 3
3. Logo
4.Ig:https://www.instagram.com/filter_beans/?hl=en
 FB:https://m.facebook.com/profile.php?id=100063709964445&_rdr
5. Delta

**Comment by Smrutismita109** [comment]
1.Raahee
2. Sr No.4
3.
![Raahee](https://user-images.githubusercontent.com/87279073/131226103-75038141-2cca-42f6-a443-51b11c8e4162.png)
4.https://raahee.in
5.Commu nity partner

**Comment by CIPHERTron** [comment]
![raahee](https://user-images.githubusercontent.com/56754747/131246087-e3e3f2f2-9c6c-46b3-b8ed-f4bd4a9a4e00.png)

@nayakastha @abhibhaw see if we can use this logo for Raahee or having that purple background is necessary?

**Comment by ORKO06** [comment]
Sr No.1

**Comment by ORKO06** [comment]
Sr No 1
https://res.cloudinary.com/dscnitrourkela/image/upload/project-oregano/sponsors/beta/iylv4cyswfjzoydb3why.png

Sr No 3
https://res.cloudinary.com/dscnitrourkela/image/upload/project-oregano/sponsors/delta/jzu4m46qrkuheumwzrcx.png

**Comment by abhibhaw** [comment]
> ![raahee](https://user-images.githubusercontent.com/56754747/131246087-e3e3f2f2-9c6c-46b3-b8ed-f4bd4a9a4e00.png)
> 
> @nayakastha @abhibhaw see if we can use this logo for Raahee or having that purple background is necessary?

You can use this!!

**Comment by abhibhaw** [comment]
> 1.Wolfram
> 2.Sr No.2
> 3.Logo
> [Hackathon Logo Wolfram 2021 resizable Vector.pdf](https://github.com/dscnitrourkela/project-oregano/files/7071161/Hackathon.Logo.Wolfram.2021.resizable.Vector.pdf)
> ![c112c850934247fc8749d0c8c68d4047-0001](https://user-images.githubusercontent.com/87279073/131226218-91494148-fed6-4b87-b04c-176ea10bfba2.jpg)
> 
> 1. https://www.wolfram.com
> 2. Gamma

do we have any other for this one??

**Comment by Smrutismita109** [comment]
Wolfram had only included this in their mail.

**Comment by padmajabhol** [comment]
> > 1.Wolfram
> > 2.Sr No.2
> > 3.Logo
> > [Hackathon Logo Wolfram 2021 resizable Vector.pdf](https://github.com/dscnitrourkela/project-oregano/files/7071161/Hackathon.Logo.Wolfram.2021.resizable.Vector.pdf)
> > ![c112c850934247fc8749d0c8c68d4047-0001](https://user-images.githubusercontent.com/87279073/131226218-91494148-fed6-4b87-b04c-176ea10bfba2.jpg)
> > 
> > 1. https://www.wolfram.com
> > 2. Gamma
> 
> do we have any other for this one??

Wolfram's logo is already displayed on the website I guess.

**Comment by abhibhaw** [comment]
Yaa cool than ignore this one!!

> > > 1.Wolfram
> > > 2.Sr No.2
> > > 3.Logo
> > > [Hackathon Logo Wolfram 2021 resizable Vector.pdf](https://github.com/dscnitrourkela/project-oregano/files/7071161/Hackathon.Logo.Wolfram.2021.resizable.Vector.pdf)
> > > ![c112c850934247fc8749d0c8c68d4047-0001](https://user-images.githubusercontent.com/87279073/131226218-91494148-fed6-4b87-b04c-176ea10bfba2.jpg)
> > > 
> > > 1. https://www.wolfram.com
> > > 2. Gamma
> > 
> > 
> > do we have any other for this one??
> 
> Wolfram's logo is already displayed on the website I guess.

**Comment by padmajabhol** [comment]
> 1.Filter_Beans
> 2. Sr No. 3
> 3. Logo
> ![Screenshot (3)](https://user-images.githubusercontent.com/87279073/131225979-339857a2-d731-4746-9da8-098d5c615936.png)
> 
> 4.Ig:https://www.instagram.com/filter_beans/?hl=en
> FB:https://m.facebook.com/profile.php?id=100063709964445&_rdr
> 5. Delta

Do they have a website? If not, we can redirect to their Instagram handle.

**Comment by spandanpatra13** [comment]
1. .xyz 
2. Sr. No. 5
3. Logo
![image](https://user-images.githubusercontent.com/89740609/132119250-d2ee579e-80f2-42da-a2ba-db626f2ec95a.png)
4. Beta

**Comment by spandanpatra13** [comment]
1. Voiceflow
2. Sr. No. 6
3. Logo
![Voiceflow White](https://user-images.githubusercontent.com/89740609/132119386-63a86f76-cf42-43e1-9119-3fa229e66d85.png)
4. Delta

**Comment by abhibhaw** [comment]
1. Koii Network
2. Sr. No. 7
3. Assets: https://drive.google.com/drive/folders/18H5KiomDb7XgJKAwJmSJGfRs31kY0mAb?usp=sharing
4. Backlink: https://koii.network/
5. Gamma Tier

**Comment by padmajabhol** [comment]
> 1. Filecoin
> 2. Sr. No. - 8
> 3. https://www.notion.so/Branding-Guidelines-c8cdd8621f0f416caf36817cc3b42dc5#bc2c8818ed924f9d900c9306456641f5
> 4. Backlink - https://filecoin.io/
> 5. Beta Tier
> 
> @padmajabhol can we do it today itself?

yep! on it.

**Comment by abhibhaw** [comment]
1. Egghead
2. Sr. No: 9
3. asset: https://raw.githubusercontent.com/dscnitrourkela/project-kiwi-archive/dev/public/images/egghead.png
4. backlink: https://egghead.io/
5. Beta Tier

**Comment by nayakastha** [comment]
1. Auth0
2. Sr. No. 10
3. asset -
4 backlink - https://auth0.com/
5. Beta Tier

**Comment by abhibhaw** [comment]
@padmajabhol Prefer Auth0 at index 0 in the beta list
