### ISSUE TITLE
Update Sponsors section

### ISSUE THREAD

**Issue by riteshsp2000** [dscnitrourkela/project-oregano#94]
A new design has been created for the sponsors' section. 
- Implement the design using css-grids.
- Make sure the entire section is responsive and the order of sponsors as per the design.
- Abstract the section as much as possible so that it is not bound to a particular layout and is easily responsive.
- size of the logos starts decreasing from the top.
-  Maintain the ratio for boxes of gamma and delta sponsors. 
- instead of just 2 in a row for delta, possibly have 3. the gamma box should be flexible and the number of sponsors in a row should adjust as per the width.
- For mobile view, it should be one below the other.

**Comment by padmajabhol** [comment]
Interested.
